### ISSUE TITLE
cppcheck-htmlreport & cppcheck-codequality

### ISSUE THREAD

**Issue by kazh000** [neszt/cppcheck-docker#6]
- cppcheck-htmlreport doesn't work because requires packages python3 and py3-pygments
-  It would be nice to add cppcheck-codequality (https://gitlab.com/ahogen/cppcheck-codequality) for gitlab cicd. install: apk add  py3-pip; pip install cppcheck-codequality

**Comment by neszt** [comment]
Unfortunately, there are several obstacles to this, on the one hand, this is a cppcheck project, and on the other hand, there is an ENTRYPOINT in the Dockerfile, which is why you can only run the cppcheck command. Unfortunately, this could not be modified to remain backwards compatible.

However, the idea is good, I will create a separate cppcheck-codequality repo for this.

**Comment by kazh000** [comment]
I run the image with the option entrypoint=[ "/bin/sh", "-c" ] and my scripts with cppcheck, cppcheck-htmlreport and cppcheck-codequality, so it doesn't require a separate image and compatible with the current image.

**Comment by neszt** [comment]
It really works, but the size of the image has increased from 16MB to 72MB, mostly because of the python3 package, which was not needed until now. Now I'm trying to convert this to binary, because this 4-5x image size is a bit confusing.

**Comment by neszt** [comment]
@kazh000 I managed to [solve it](https://github.com/neszt/cppcheck-docker/commit/a1fadbb53f7502291c6948935c31923cae1820ff) with a relatively small increase in size, could you test whether it works properly in your environment?

**Comment by kazh000** [comment]
Great! It works perfectly. Thank you very much.
